#!/usr/bin/env bash
# a script to install nginx to the server

if [ $# -ne 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

fpath=$1
ip=$2
uname=$3
keypath=$4

scp StrictHostKeyChecking=no -i "$keypath" "$fpath" "$uname@$ip":~/
