#!/usr/bin/env bash
# bash script to install and configure nginx
# configure it to listen on port 80

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
# Configure Nginx to listen on port 80
sudo sed -i 's/listen 80;/listen 80;/g' /etc/nginx/sites-enabled/default
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www/html

# create a copy
sudo cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
echo 'Hello World!' > /var/www/html/index.nginx-debian.html

sudo service nginx restart
