#!/usr/bin/env bash
# bash script to install and configure nginx
# configure it to listen on port 80

sudo apt-get -y update

wget http://nginx.org/packages/ubuntu/pool/nginx/n/nginx/nginx_1.4.6-1ubuntu3.7_all.deb

# Install the package using dpkg
sudo apt-get -y update

# Install any missing dependencies
sudo apt-get -y install nginx

# Configure Nginx to listen on port 80
sudo sed -i 's/listen 80;/listen 80;/g' /etc/nginx/sites-enabled/default
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www/html


echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
# Clean up downloaded package
rm nginx_1.4.6-1ubuntu3.7_all.deb

sudo service nginx restart
