#!/usr/bin/env bash
# bash script to install and configure nginx
# configure it to listen on port 80

# Define the redirection configuration
redirection_config="location /redirect_me {
    return 301 ;https://www.youtube.com/watch?v=QH2-TGUlwu4 PERMANENT;
}"

sudo apt-get -y update

wget http://nginx.org/packages/ubuntu/pool/nginx/n/nginx/nginx_1.4.6-1ubuntu3.7_all.deb

# Install the package using dpkg
sudo dpkg -i nginx_1.4.6-1ubuntu3.7_all.deb

# Install any missing dependencies
sudo apt-get -f install -y


echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
# Configure Nginx to listen on port 80
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www/html


# Add redirection configuration to Nginx default site configuration
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default

# Clean up downloaded package
rm nginx_1.4.6-1ubuntu3.7_all.deb

sudo service nginx restart
