#!/usr/bin/env bash
# bash script to install and configure nginx


# installing nginx
sudo apt-get -y update
sudo apt-get -y install nginx


echo "Hello World" | sudo tee /var/www/html/index

# start nginx service
sudo service nginx start

sed -i '/server_name/a 
	location /redirect_me {
		https://www.youtube.com/ permanent;
	}' /etc/nginx/sites-available/default

if [ -f /etc/nginx/sites-enabled/default ]; then
    sudo rm /etc/nginx/sites-enabled/default
fi

# Create a symlink to the default configuration file
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default


# Start Nginx service
sudo service nginx restart
