#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on

# Define the hostname variable
hostname=$(hostname)

sudo apt-get -y update
sudo apt-get -y install nginx

# echo "hello world" to index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# start nginx server
sudo service nginx start

# for the custom_404.html page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null

# edit the default configuration file
sudo sed -i '/server_name/ {
    a\
    add_header $hostname
    error_page 404 /custom_404.html;\
    location /redirect_me {\
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\
    }
    :a
    n; ba
}' /etc/nginx/sites-available/default

# Check if the default configuration file is present in sites-enabled
if [ -f /etc/nginx/sites-enabled/default ]; then
	sudo rm /etc/nginx/sites-enabled/default
fi

# Create a symlink to the default configuration file
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

sudo service nginx restart
