#!/usr/bin/env bash
# debugging nginx server

# create a link between the sites-availabe and site enabled
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# restart or reload nginx
service nginx reload
