#!/usr/bin/env bash
# nginx must be running as nginx user
sudo sed -i "s/#user www-data;/user nginx;/" /etc/nginx/nginx.conf
sudo sed -i "s/listen 80 default_server/listen 8080 default_server/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf 
sudo service nginx start
